import Breadcrumbs from "@/components/breadcrumbs/Breadcrumbs";
import s from "./page.module.css"
import Filter from "@/components/aside/filter/Filter";
import { Suspense } from "react";
import Link from "next/link";
import { prisma } from "@/lib/data";

export const metadata = {
  title: "Shop | Next App",
  description: "Generated by create next app",
};


async function CategoryList() {
  const categories = await prisma.category.findMany();

  return (
    <ul>
      { categories.map((category) => (
        <li key={category.id}>
          <Link 
                className={s.link} 
                href={`/catalog/category/${category.slug}`}>
                { category.title }
            </Link>
        </li>
      ))}
    </ul>
  )
};

function Loading() {
  return <h2>🌀 Loading...</h2>;
}

export default function Shop() {
  
  return (
    <section>
      <Breadcrumbs h1="Каталог" />
      <div className={s.container}>
        <aside className={s.aside}>
          <Filter />
          </aside>
        <div className={s.body}>
          <Suspense fallback={<Loading />}>
            <CategoryList />
          </Suspense>
        </div>
      </div>
    </section>
  );
};




