import styles from './page.module.css'
import Breadcrumb from '@/components/breadcrumb/Breadcrumb'
import Filter from '@/components/aside/filter/Filter'
import { H1 } from '@/components/headling/H1'
import { Metadata } from 'next'
import Catalog from '@/components/catalog/Catalog'

export const metadata: Metadata = {
	title: 'Каталог | Next App',
	description: 'Generated by create next app',
}

export default function Page() {
	return (
		<>
			<Breadcrumb>
				<H1 title='Каталог' />
			</Breadcrumb>
			<div className={styles.container}>
				<aside className={styles.aside}>
						<Filter />
					</aside>
					<div className={styles.body}>
							<Catalog />
					</div>
			</div>
		</>
	)
}