import Breadcrumbs from "@/components/breadcrumbs/Breadcrumbs";
import styles from "./page.module.css"
import Filter from "@/components/aside/filter/Filter";
import Link from "next/link";
import Image from "next/image";
import { Suspense } from "react";
import { prisma } from "@/db/prisma";
import { Loading } from "@/components/loading/Loading";

export const metadata = {
  title: "Shop | Next App",
  description: "Generated by create next app",
};

export default async function Catalog() {
  return (
    <section>
      <Breadcrumbs h1="Каталог" />
      <div className={styles.container}>
        <aside className={styles.aside}>
          <Filter />
          </aside>
        <div className={styles.body}>
          <div className={styles.category_img}>
            <div className={styles.category_info}>
              <h3>Пестициды</h3>
              <Link className={styles.all_link} href="#">
                Смотреть все<span className={styles.all_icon}> &#5125;</span></Link>
            </div>
            <Image src="/pesticides-juk.jpeg" 
                alt="pesticides-juk" 
                width={400} 
                height={200} />
            </div>
          <div className={styles.category_list}>
            <Suspense fallback={ <Loading/> }>
              <CategoryList />
            </Suspense>
          </div>
        </div>
      </div>
    </section>
  );
};

async function CategoryList() {
  const category = await prisma.category.findMany();

  return (
      <ul>
        { category?.map((category) => (
            <li key={category.id}>
              <Link className={styles.category_link} href={`/catalog/category/${category.slug}`}>
                  { category.title }
              </Link>
          </li>
          ))}
      </ul>
  )};
