import Breadcrumbs from "@/components/breadcrumbs/Breadcrumbs";
import styles from "./page.module.css"
import Filter from "@/components/aside/filter/Filter";
import type { Metadata } from "next";
import { Suspense } from "react";
import Link from "next/link";
import { prisma } from "@/lib/data";

export const metadata: Metadata = {
  title: "Shop | Next App",
  description: "Generated by create next app",
};

async function List() {
  const categoryAll = await prisma.category.findMany();

  return (
    <ul>
      { categoryAll.map((category: any) => (
        <li key={category.id}>
          <Link 
                className={styles.link} 
                href={`/shop/category/${category.catSlug}`}>
                { category.title }
            </Link>
        </li>
      ))}
    </ul>
  )
};

export default function Shop() {
  
  return (
    <section>
      <Breadcrumbs h1="Shop" />
      <div className={styles.container}>
        <aside className={styles.aside}>
          <Filter />
          </aside>
        <div className={styles.body}>
          <Suspense fallback={"Loading..."}>
            <List />
          </Suspense>
        </div>
      </div>
    </section>
  );
};
